### ISSUE TITLE
[BUG] Wallet core dump after power fail

### ISSUE THREAD

**Issue by 7queue** [EpicCash/epic-wallet#85]
The system power failed, after reboot the wallet gives me this, listen mode works.
Is there a db corruption, besides starting over, is there a way to check the integrity of the db?

$ epic-wallet info
Password: 
2023-06-25 10:14:44.995 WARN Scanning - 0% complete
2023-06-25 10:14:45.005 WARN Scanning - 99% complete
2023-06-25 10:14:45.013 WARN Scanning - 99% complete
2023-06-25 10:14:45.013 WARN Scanning Complete

____ Wallet Summary Info - Account 'default' as of height 2022509 ____

Segmentation fault (core dumped)

Node 3.4.0
Wallet 3.4.0
Miner (fails to build, sub modules out of sync)
Linux 5.19.0-45-generic #46~22.04.1-Ubuntu
rustc 1.70.0 (90c541806 2023-05-31)
cargo 1.70.0 (ec8a8a0ca 2023-04-25)

[epic-wallet.log.md](https://github.com/EpicCash/epic-wallet/files/11859968/epic-wallet.log.md)
[epic-wallet.toml.md](https://github.com/EpicCash/epic-wallet/files/11859969/epic-wallet.toml.md)

**Comment by who-biz** [comment]
You need to use Rust 1.67 or less. Segfault is happening there due to incompatibility with Rust 1.70 and PrettyPrinted table displayed by `epic-wallet info` command.

changes were recently made to support 1.67. 

I am not sure what upper bound wrt to rust version. But, prior to those changes (which resolve exactly this issue) segfault was present any rust version in excess of 1.64.

this is an old issue, so I will assume you figured it out

**Comment by who-biz** [comment]
Power failure was incidental. It looks like you may have updated your rust toolchain afterward.
